data/images/db
paulms1/collectionProject pull request #1
Opened 2020-02-03 14:47 UTC by paulms1

set up of database + assets

2020-02-03 14:58 UTC, ashleycoles approved these changes
Looks good to me! Just make sure that before you merge this request you change it to merge into your story branch instead of master. Should be able to do that just under the pull request name

2020-02-04 16:39 UTC, robings requested changes
This looks good on all browsers. Just a few comments. Mainly it would be worth looking at the css, as some of it doesn't appear to affect the display.

2020-02-04 16:39 UTC, robings commented on fe/index.php
> +        <link rel="stylesheet" type="text/css" href="styles.css">
add `<meta name="viewport" content="width=device-width">`

2020-02-04 16:39 UTC, robings commented on fe/styles.css
> +    height: 300px;
could be better to have a minimum height rather than a height definition

2020-02-04 16:39 UTC, robings commented on fe/styles.css
> +    height: 150px;
as above, it might be better to have a min-height definition rather than height.

2020-02-04 16:39 UTC, robings commented on fe/styles.css
> +        display: block;
here the only thing that changes anything in the browser is the width definition.

2020-02-04 16:39 UTC, robings commented on data/data.txt
> +
is this a preparatory file? If so you could gitignore it

2020-02-05 09:13 UTC, merged